name: Get the current workflow run URL
description: Get the current workflow run URL, which is not available by default in the GitHub Actions context
inputs: {}

outputs:
  url:
    value: ${{ fromJSON(steps.script.outputs.result).workflow_url }}

runs:
  using: "composite"
  steps:
    - id: script
      uses: actions/github-script@v7
      env:
        REPOSITORY: ${{ github.repository }}
        SERVER_URL: ${{ github.server_url }}
        WORKFLOW: ${{ github.workflow }}
        RUN_ID: ${{ github.run_id }}
        RUN_ATTEMPT: ${{ github.run_attempt }}
      with:
        script: |
          let {REPOSITORY, SERVER_URL, WORKFLOW, RUN_ID} = process.env

          const run_url = `${SERVER_URL}/${REPOSITORY}/actions/runs/${RUN_ID}/attempts/${RUN_ATTEMPT}`

          return {
            run_url
          }
