name: Prepare metadata with multilevel support
description: Get the current workflow run URL, which is not available by default in the GitHub Actions context
inputs:
  meta:
    description: "Existing metadata JSON string"
    required: false
    default: ""

outputs:
  json:
    value: ${{ steps.script.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: script
      uses: actions/github-script@v7
      env:
        META: ${{ inputs.meta }}
      with:
        script: |
          let { META } = process.env

          let metaData;

          if (META === '') {
            metaData = {};
          } else {
            metaData = JSON.parse(META);
          }
          
          if (!Array.isArray(metaData.workflows)) {
            metaData.workflows = []
          }
          
          console.log(JSON.stringify(context, null, 2));
          
          metaData.workflows.push(
            {
              "parent-workflow-name":`${context.workflow}`,
              "parent-workflow-url":`${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/attempts/${context.runAttempt}`,
              "parent-workflow-repo":`${context.repo.owner}/${context.repo.repo}`
            }
          );
          
          return JSON.stringify(metaData);
