name: Prepare metadata with multilevel support
description: Get the current workflow run URL, which is not available by default in the GitHub Actions context
inputs:
  meta:
    description: "Existing metadata JSON string"
    required: false
    default: ""

outputs:
  json:
    value: ${{ steps.script.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: script
      uses: actions/github-script@v7
      env:
        META: ${{ inputs.meta }}
      with:
        script: |
          let { META } = process.env

          let metaData;

          metaData = JSON.parse(META);
          
          if (typeof metaData !== object) {
            metaData = {};
          }
          
          if (!Array.isArray(metaData.workflows)) {
            metaData.workflows = []
          }
          
          metaData.workflows.push(
            {
              "parent-workflow-name":`${github.workflow}`,
              "parent-workflow-url":`${github.server_url}/${github.repository}/actions/runs/${github.run_id}/attempts/${github.run_attempt}`,
              "parent-workflow-repo":`${github.repository}`
            }
          );
          
          return JSON.stringify(metaData);
