name: Custom dispatch action with summary and metadata support
description: Custom dispatch action with summary and metadata support
inputs:
  meta:
    # JSON format
    # { workflows: [
    #   {
    #     parent-workflow-name: string,
    #     parent-workflow-url: string
    #   }
    # ]}
    description: "Metadata stringified JSON to parse"
    required: false
    default: ""
  workflow-file:
    description: "Workflow file name"
    required: true
  workflow-name:
    description: "Workflow name"
    required: true
  token:
    description: "GitHub token"
    required: true
  workflow-inputs:
    description: "Workflow inputs as partial JSON without the trailing comma"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Prepare meta data
      id: meta
      uses: ./.github/actions/prepare-meta
      with:
        meta: ${{ inputs.meta }}

    - name: Merge inputs
      id: merge-inputs
      env:
        META_JSON: ${{ steps.meta.outputs.json }}
        WORKFLOW_INPUTS_JSON: ${{ inputs.workflow-inputs }}
      uses: actions/github-script@v7
      with:
        script: | 
          const { META_JSON, WORKFLOW_INPUTS_JSON } = process.env;
          
          const parsedInputs = JSON.parse(WORKFLOW_INPUTS_JSON);
          const parsedMeta = JSON.parse(JSON.parse(META_JSON));
          
          console.log(`[DEBUG]Parsed inputs: ${JSON.stringify(parsedInputs)}`);
          console.log(`[DEBUG]Parsed meta: ${JSON.stringify(parsedMeta)}`);
          
          const inputs = {...parsedInputs, meta: JSON.stringify({...parsedMeta})}; 
          
          return JSON.stringify(inputs);

    - uses: the-actions-org/workflow-dispatch@v4
      id: dispatch
      with:
        workflow: ${{ inputs.workflow-file }}
        token: ${{ inputs.token }}
        wait-for-completion: true
        display-workflow-run-url: true
        wait-for-completion-interval: 10s
        inputs: |-
          ${{ fromJSON(steps.merge-inputs.outputs.result) }}

    - name: Summary
      shell: bash
      run: |
        echo 'Dispatched [${{inputs.workflow-name}}](${{steps.dispatch.outputs.workflow-url}}). Result: `${{steps.dispatch.outputs.workflow-conclusion}}`' >> $GITHUB_STEP_SUMMARY