name: Custom dispatch action with summary and metadata support
description: Custom dispatch action with summary and metadata support
inputs:
  meta:
    description: "Metadata JSON"
    required: false
    default: ""
  workflow-file:
    description: "Workflow file name"
    required: true
  workflow-name:
    description: "Workflow name"
    required: true
  token:
    description: "GitHub token"
    required: true
  workflow-inputs:
    description: "Workflow inputs"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Meta data
      id: meta
      uses: ./.github/actions/prepare-meta
      with:
        meta: ${{ inputs.meta }}

    - uses: the-actions-org/workflow-dispatch@v4
      id: dispatch
      with:
        workflow: ${{ inputs.workflow-file }}
        token: ${{ inputs.token }}
        wait-for-completion: true
        display-workflow-run-url: true
        wait-for-completion-interval: 10s
        inputs: |-
          {
            ${{ inputs.workflow-inputs }},
            "meta": ${{steps.meta.outputs.json}}
          }

    - name: Summary
      shell: bash
      run: |
        echo 'Dispatched [${{inputs.workflow-name}}](${{steps.dispatch.outputs.workflow-url}}). Result: `${{steps.dispatch.outputs.workflow-conclusion}}`' >> $GITHUB_STEP_SUMMARY