# multi repo dispatch example
name: Example 2 - main

on:
  workflow_dispatch:
    inputs: {}

permissions:
  actions: write

defaults:
    run:
        shell: bash

jobs:
  main-job:
    name: Main dispatch job
    runs-on: ubuntu-latest
    steps:
      - name: Meta data
        id: meta
        run: echo 'json={
            \"parent-workflow-name\":\"${{github.workflow}}\",
            \"parent-workflow-url\":\"${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}/attempts/${{github.run_attempt}}\",
            \"parent-workflow-repo\":\"${{github.repository}}\"
          }' >> $GITHUB_OUTPUT

      - uses: the-actions-org/workflow-dispatch@v4
        id: dispatch
        with:
          workflow: ex1-app1.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true
          display-workflow-run-url: true
          repo: roamingowl/gh-workflow-dispatch-navigation-second-example
          wait-for-completion-interval: 10s
          inputs: |-
            {
              "build": "true",
              "test": "true",
              "meta": "${{steps.meta.outputs.json}}"
            }

      - name: Summary
        run: |
          echo 'Dispatched [second_repo/Example 2 - App 1](${{steps.dispatch.outputs.workflow-url}}). Result: `${{steps.dispatch.outputs.workflow-conclusion}}`' >> $GITHUB_STEP_SUMMARY