# multi level dispatch example
name: Example 3 - Main

on:
  workflow_dispatch:
    inputs: { }

permissions:
  actions: write

defaults:
  run:
    shell: bash

jobs:
  main-job:
    name: Main dispatch job
    runs-on: ubuntu-latest
    steps:
      - name: Meta data
        id: meta
        run: echo 'json={
          \"workflows\":[
          {
            \"parent-workflow-name\":\"${{github.workflow}}\",
            \"parent-workflow-url\":\"${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}/attempts/${{github.run_attempt}}\",
            \"parent-workflow-repo\":\"${{github.repository}}\"
          }
          ]}' >> $GITHUB_OUTPUT

      - uses: the-actions-org/workflow-dispatch@v4
        id: dispatch
        with:
          workflow: ex3-middle.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true
          display-workflow-run-url: true
          wait-for-completion-interval: 10s
          inputs: |-
            {
              "app1": "true",
              "meta": "${{steps.meta.outputs.json}}"
            }

      - name: Summary
        if: ${{ always() }}
        run: |
          echo 'Dispatched [Example 3 - Middle](${{steps.dispatch.outputs.workflow-url}}). Result: `${{steps.dispatch.outputs.workflow-conclusion}}`' >> $GITHUB_STEP_SUMMARY