name: "Example 4 - App 1"

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build the library"
        required: true
        default: "true"
      test:
        description: "Run the tests"
        required: true
        default: "true"
      meta:
        description: "Metadata"
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  parent-info:
    name: Parent Info
    if: ${{ inputs.meta != '' && fromJSON(inputs.meta).workflows != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/parent-info
        id: summary
        with:
          meta: ${{ inputs.meta }}

      - name: Print parent workflow url
        if: ${{ steps.summary.outputs.message != '' }}
        env:
          MESSAGE: ${{ fromJSON(steps.summary.outputs.message) }}
        run: |
          while IFS= read -r line; do
            echo $line >> $GITHUB_STEP_SUMMARY
          done <<< "$MESSAGE"   

  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ inputs.test == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Fake test
        shell: bash
        run: echo "Testing..."

  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ inputs.build == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Fake build
        shell: bash
        run: echo "Bundling..."