name: "Example 4 - 2nd level"

on:
  workflow_dispatch:
    inputs:
      app1:
        description: "App 1 processing"
        required: true
        default: "true"
      meta:
        description: "Metadata from the previous workflow"
        required: false
        default: ""

permissions:
  actions: write

defaults:
  run:
    shell: bash

jobs:
  parent-info:
    name: Parent Info
    # process meta only of there are any
    if: ${{ inputs.meta != '' && fromJSON(inputs.meta).workflows != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/parent-info
        with:
          meta: ${{ inputs.meta }}

  app1:
    name: Middle dispatch job
    runs-on: ubuntu-latest
    if: ${{ inputs.app1 == 'true' }}
    steps:
      - uses: actions/checkout@v4

      # 2nd level dispatch
      - name: Dispatch
        uses: ./.github/actions/dispatch-with-summary
        with:
          meta: ${{ inputs.meta }}
          workflow-inputs: |
            {
              "test": "true",
              "build": "true"
            }
          workflow-name: Example 4 - App 1
          workflow-file: ex4-app1.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
